# S3-Only Configuration for HK Government PDF Crawler
# This configuration uploads directly to S3 without local storage

departments:
  buildings_department:
    name: "Buildings Department"
    seed_urls:
      - "https://www.bd.gov.hk/en/resources/codes-and-references/codes-and-design-manuals/index.html"
      - "https://www.bd.gov.hk/en/resources/codes-and-references/practice-notes-and-circular-letters/index_pnap.html"
    max_depth: 3
    max_pages: 500
    time_limit: 1800

  labour_department:
    name: "Labour Department"
    seed_urls:
      - "https://www.labour.gov.hk/eng/public/content2_8.htm"
      - "https://www.labour.gov.hk/eng/legislat/contentB3.htm"
    max_depth: 2
    max_pages: 300
    time_limit: 1200

  environmental_protection_department:
    name: "Environmental Protection Department"
    seed_urls:
      - "https://www.epd.gov.hk/epd/english/environmentinhk/air/guide_ref/guide_ref.html"
      - "https://www.epd.gov.hk/epd/english/environmentinhk/water/guide_ref/guide_ref.html"
    max_depth: 2
    max_pages: 400
    time_limit: 1500

# Standard settings
settings:
  delay_between_requests: 1.5
  max_concurrent_downloads: 3
  respect_robots_txt: true
  user_agent: "HK-PDF-Crawler/1.0"
  enable_browser_automation: true
  request_timeout: 30

# S3-only storage (no local files)
storage:
  local_path: null  # No local storage
  organize_by_department: true
  s3_enabled: true
  s3_bucket: "your-pdf-bucket"  # Replace with your bucket name
  s3_prefix: "hk-government-pdfs/"

# Note: Make sure AWS credentials are configured:
# - AWS CLI: aws configure
# - Environment variables: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
# - IAM roles (for EC2 instances)